from pathlib import Path

PROJECT_NAME = "cypher"
VERSION = "0.4.1"

MAGIC = "CYPHER"
HEADER_VERSION = 4

PAYLOAD_MODE = "ANY_FILE_LOSSLESS_PAYLOAD"
CHECKSUM_ALGORITHM = "SHA256"
COMPRESSION_ALGORITHM = "zlib"

DEFAULT_SAMPLE_RATE = 44_100
DEFAULT_AUDIO_FORMAT = "flac"
DEFAULT_COMPRESSION_LEVEL = 9

LOSSLESS_AUDIO_OUTPUT = {".wav", ".flac"}
UNSAFE_AUDIO_OUTPUT = {".mp3"}

DATA_DIR = Path("data")
INPUT_DIR = DATA_DIR / "input"
AUDIO_DIR = DATA_DIR / "audio"
OUTPUT_DIR = DATA_DIR / "output"
