from pathlib import Path

PROJECT_NAME = "cypher"
VERSION = "0.3.0"

MAGIC = "CYPHER"
HEADER_VERSION = 3

COLOR_MODE = "RGB"
PIXEL_MODE = "RGB_LOSSLESS_PAYLOAD"
CHECKSUM_ALGORITHM = "SHA256"
COMPRESSION_ALGORITHM = "zlib"

DEFAULT_SAMPLE_RATE = 44_100
DEFAULT_AUDIO_FORMAT = "flac"
DEFAULT_COMPRESSION_LEVEL = 9

SUPPORTED_INPUT_IMAGES = {".png", ".jpg", ".jpeg", ".bmp"}
SUPPORTED_AUDIO_OUTPUT = {".wav", ".flac"}

DATA_DIR = Path("data")
INPUT_DIR = DATA_DIR / "input"
AUDIO_DIR = DATA_DIR / "audio"
OUTPUT_DIR = DATA_DIR / "output"
