from pathlib import Path

PROJECT_NAME = "cypher"
VERSION = "0.2.0"

DEFAULT_SAMPLE_RATE = 8_000
DEFAULT_PIXEL_DURATION = 0.002
DEFAULT_AMPLITUDE = 0.25

R_FREQ = 500.0
G_FREQ = 1500.0
B_FREQ = 2500.0

MAGIC = "CYPHER"
HEADER_VERSION = 2
COLOR_MODE = "RGB"
PIXEL_MODE = "RGB_FIXED_FREQ_AMPLITUDE"
CHECKSUM_ALGORITHM = "SHA256"

SUPPORTED_INPUT_IMAGES = {".png", ".jpg", ".jpeg", ".bmp"}
SUPPORTED_AUDIO_OUTPUT = {".wav", ".flac"}

DATA_DIR = Path("data")
INPUT_DIR = DATA_DIR / "input"
AUDIO_DIR = DATA_DIR / "audio"
OUTPUT_DIR = DATA_DIR / "output"
